namespace: koonix
name: compose_projects
version: 0.3.0
description: Roles for running Docker Compose projects.
repository: https://github.com/koonix/ansible-compose-projects
issues:     https://github.com/koonix/ansible-compose-projects/issues
authors: [ 'koonix <me@koonix.org>' ]
license: [ 'MIT' ]
readme: README.md
tags:
  - docker
  - docker-compose
