- name: Create dirs
  ansible.builtin.file:
    state: directory
    path: '{{ item.path }}'
    mode: '{{ item.mode | default("700") }}'
    owner: root
    group: root
  loop:
    - path: '{{ compose_projects_lib_dir }}'

- name: Remove extraneous instances
  ansible.builtin.shell:
    chdir: '{{ dir }}'
    cmd: |
      for path in * .*; do
        [ ! -e "$path" ] && continue
        case $path in
          {{ ( [ '.', '..' ] + keep ) | map('ansible.builtin.quote') | join('|') }}) ;;
          *)
            if [ -e "$path/compose.yml" ]; then
              docker compose --project-directory="$path" down
            fi
            rm -r -- "$path"
            echo removed
          ;;
        esac
      done
  register: rmextra
  changed_when: "'removed' in rmextra.stdout"
  vars:
    # IMPORTANT: update the 'keep' list to reflect the files that we want to keep
    dir: '{{ compose_projects_lib_dir }}'
    keep: '{{ compose_projects | map(attribute="name") }}'

- name: Setup instances
  ansible.builtin.include_tasks:
    file: setup.yml
  vars:
    instance_dir: '{{ compose_projects_lib_dir }}/{{ instance.name }}'
  loop: '{{ compose_projects }}'
  loop_control:
    loop_var: instance
