- name: Converge
  hosts: all
  become: true
  roles:
    - koonix.docker.docker
    - koonix.compose_projects.compose_projects

  vars:

    compose_projects:

      - name: compose-1
        pre_start: [ echo, hi ]
        compose:
          services:
            busybox:
              image: busybox:1
              command: [ sleep, inf ]
              restart: unless-stopped

      - name: compose-2
        post_start: [ echo, hi ]
        compose:
          services:
            busybox:
              build:
                context: .
              restart: unless-stopped
        assets:
          - name: Dockerfile
            post_update: [ build ]
            content: |
              FROM busybox:1
              CMD [ "sleep", "inf" ]
