- name: Converge
  hosts: all
  become: true
  roles:
    - koonix.docker.docker
    - koonix.compose_projects.compose_projects

  vars:

    compose_projects:

      - name: compose-1
        pre_start:
          - [ sh, -c, 'echo text >> /pre-start' ]
        compose:
          services:
            busybox:
              image: busybox:1
              container_name: compose-1
              command: [ sleep, inf ]
              restart: unless-stopped

      - name: compose-2
        post_start:
          - [ sh, -c, 'echo text >> /post-start' ]
        compose:
          services:
            busybox:
              build:
                context: .
              container_name: compose-2
              restart: unless-stopped
        assets:
          - dest: Dockerfile
            content: |
              FROM busybox:1
              COPY test-file.txt /file
              CMD [ "sleep", "inf" ]
            pre_update:
              - [ sh, -c, 'echo text >> /pre-update' ]
              - [ sh, -c, 'echo text >> /pre-update' ]
            post_update:
              - build
              - [ sh, -c, 'echo text >> /post-update' ]
              - [ sh, -c, 'echo text >> /post-update' ]

          - src: test-file.txt
            pre_update:
              - [ sh, -c, 'echo text >> /pre-update' ]
              - [ sh, -c, 'echo text >> /pre-update' ]
            post_update:
              - [ sh, -c, 'echo text >> /post-update' ]
              - [ sh, -c, 'echo text >> /post-update' ]

          - src: test-template.txt
            type: template
            no_log: true
            pre_update:
              - [ sh, -c, 'echo text >> /pre-update' ]
              - [ sh, -c, 'echo text >> /pre-update' ]
            post_update:
              - [ sh, -c, 'echo text >> /post-update' ]
              - [ sh, -c, 'echo text >> /post-update' ]

          - src: test-dir
            pre_update:
              - [ sh, -c, 'echo text >> /pre-update' ]
              - [ sh, -c, 'echo text >> /pre-update' ]
            post_update:
              - [ sh, -c, 'echo text >> /post-update' ]
              - [ sh, -c, 'echo text >> /post-update' ]
