- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Verify
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          {% raw %}

          set -euE -o pipefail
          trap 'echo "${0##*/}: failed @ line $LINENO: $BASH_COMMAND"' ERR

          for file in /pre-start /post-start /pre-update /post-update; do
            echo "$file"
            [ -f "$file" ]
            [ "$(cat "$file")" = 'text' ]
          done

          for container in compose-1 compose-2; do
            echo "$container"
            state=$(docker container inspect --format '{{.State.Running}}' "$container")
            [ "$state" = 'true' ]
          done

          [ '755' = $(stat --format=%a /var/lib/ansible-compose-projects/compose-1) ]
          [ '700' = $(stat --format=%a /var/lib/ansible-compose-projects/compose-2) ]
          [ 'template file' = "$(cat /var/lib/ansible-compose-projects/compose-2/test-template.txt)" ]
          [ -f /var/lib/ansible-compose-projects/compose-2/test-dir/test-file.txt ]

          {% endraw %}
      changed_when: false
